### ISSUE TITLE
Batch size

### ISSUE THREAD

**Issue by 953951975** [caiyuanhao1998/BiSCI#1]
您好，请问为什么要将batchsize设置为2呢，我尝试将其设置为16，但是在第一个epoch运行到一半的时候报错：RuntimeError: CUDA error: an illegal memory access was encountered；但是将batchsize设置为2后又可以正常运行

**Comment by caiyuanhao1998** [comment]
hello，我把batch size设置为2是因为实验室机器显存大小的限制，我用的2080，所以设置小一点让它能够跑起来。我们的模型没有batch size，所以设置多大的batch size理论上是没啥太大影响的。
