### ISSUE TITLE
BiSRNet训练部分是否需要mask

### ISSUE THREAD

**Issue by roshameow** [caiyuanhao1998/BiSCI#2]
您好，我发现在real部分训练代码里，BiSRNet其实并没用到mask的数据，是不是是否输入mask都不重要呢？
https://github.com/caiyuanhao1998/BiSCI/blob/master/real/train_code/architecture/BiSRNet.py

还有在option里面，crop_size默认设置成96，这是不是太小了？实际训练用这个size可以吗？
https://github.com/caiyuanhao1998/BiSCI/blob/master/real/train_code/option.py

**Comment by caiyuanhao1998** [comment]
感谢关注。
对的，real训练的时候，不再依赖于mask了。crop_size 变小，但是训练样本数变多了。
我们的这个二值网络在真实场景上训练时还可以过滤噪声（因为信号被压缩成两个值），非常鲁棒

减小 patch size 还有一个好处就是训练时的显存占用比较低，欢迎尝试一下

如果觉得有帮助的话，帮我们点点star支持一下，感谢~

https://github.com/caiyuanhao1998/BiSCI

https://github.com/caiyuanhao1998/MST
